### ISSUE TITLE
Alignment of serial sections

### ISSUE THREAD

**Issue by JLiLab** [JEFworks-Lab/STalign#12]
Thank you for creating this fantastic method. I was wondering if STalign can be used to align serial sections. 

Best, 

James

By the way, the tutorials are well written and easy to follow. However, I had difficulties to understand how to use the python script to create landmarks and load the annotated images back into the notebook.

**Comment by kpclifton** [comment]
Dear James,

Thank you for your appreciation of STalign and for your question about using it to align serial sections.

Yes, STalign can be used to align serial sections. We have added two tutorials [Aligning heart ST data from ISS](https://jef.works/STalign/notebooks/heart-alignment.html) and [Aligning partially matched, serial, single-cell resolution breast cancer spatial transcriptomics data from Xenium](https://jef.works/STalign/notebooks/xenium-xenium-alignment.html) that demonstrate alignment of two serial sections of the developing human heart and two serial sections of human breast cancer, respectively. If you would like to align three or more serial sections, we suggest using STalign to do series of pairwise alignments.

Regarding creating landmarks, we have since provided an expanded explanation of how to use `point_annotator.py` in the command line to annotate landmarks points and how to load the resulting `.npy` files into the notebook in the tutorial [Aligning single-cell resolution spatial transcriptomics data to H&E staining image from Visium](https://jef.works/STalign/notebooks/merfish-visium-alignment-with-point-annotator.html).


Best, 
Kalen
