### ISSUE TITLE
Downsizing of .tif to .png for post-Xenium 1 H&E

### ISSUE THREAD

**Issue by estellad** [JEFworks-Lab/STalign#16]
Hi there,

Thank you for the great method! I wonder what tool have you used to downsize the .tif (1.7GB, 20511px * 27587px) to a dimension of 2051px * 2759px? Just by saving it as .png does not reduced the px level dimension, and only reduce the size to half (780.9 MB), which is still too large to read in. I have also tried some online converter or python converter. Both are too large to read in. 

Is it a concern if the scale on both x and y are divided by 10? Or as long as we preserve the ratio, it's okay to downsize? Thank you for your help! :D

Sincerely,
Estella

**Comment by JEFworks** [comment]
Dear Estella,

Good to hear from you. Thanks for reaching out.

While this question is a bit beyond the scope of our STalign tool, you can in theory use image editing software such as ImageJ/FIJI or even Photoshop/GIMP to rescale images (https://forum.image.sc/t/best-way-to-scale-high-resolution-images-without-losing-information/1129). There is always a function being applied when you downsize (Bilinear Interpolation, Lanczos Resampling, etc) even if you are preserving the ratio that will result in some loss of information. But for the purposes of alignment with STalign, because we align based on structural similarity, as long as the general structural features of the image are still visible after resizing, it should be ok.

Hope that helps,
Jean

**Comment by estellad** [comment]
Dear Jean,

Thank you very much for your resources and suggestions! Yes, I figured that it's important to keep the ratio. If the scaling is not 0.1, the landmarks have to be reselected. I tried using Fiji to resize, and it works well as the tutorial. Thank you!

Sincerely,
Estella
