### ISSUE TITLE
[Enhancement] Automatically subset to the common region between partially overlapping replicates

### ISSUE THREAD

**Issue by estellad** [JEFworks-Lab/STalign#17]
Hi there,

It's me again :) Thank you for the great package! I think one small enhancement can be implemented is to automatically return the common region between two overlapping regions after STalign.
 
For example in the Xenium replicate example: 
![image](https://github.com/JEFworks-Lab/STalign/assets/29610938/7988446d-ee62-464a-9d90-e6e39e916b61)

This was done in [SpatialData manuscript](https://www.biorxiv.org/content/10.1101/2023.05.05.539647v1.full.pdf) as well:
![image](https://github.com/JEFworks-Lab/STalign/assets/29610938/8f8fe22b-bcb9-4e7c-9da4-1ab6123a4c4c)

[Here is a suggestion](https://stackoverflow.com/questions/57885406/get-the-coordinates-of-two-polygons-intersection-area-in-python) on how to find the polygon coordinates of the common region, and if cells/spots are outside of the polygon, we can exclude them. 

Thank you for your help! Looking forward to hearing from you!

Sincerely,
Estella

**Comment by JEFworks** [comment]
Dear Estella,

Thanks for the suggestion and helpful references!

You may recall from the STalign manuscript (https://www.biorxiv.org/content/10.1101/2023.04.11.534630v2) that our objective function includes a mixture model component W that seeks to predict which parts of the rasterized dataset are in the background, artifact, or matching component. You can actually use this matching-score to pull out the regions that 'match'. You can check out the online supplementary methods for more details on how this is done mathematically speaking. 
<img width="365" alt="Screen Shot 2023-10-10 at 6 48 22 PM" src="https://github.com/JEFworks-Lab/STalign/assets/8975944/326e614c-0a0c-4985-af4c-4c6c1b55f22b">

More practically, we show how this is done in the MERFISH to Visium alignment notebook (https://jef.works/STalign/notebooks/merfish-visium-alignment-with-point-annotator.html) 
<img width="571" alt="Screen Shot 2023-10-10 at 6 45 35 PM" src="https://github.com/JEFworks-Lab/STalign/assets/8975944/a0bd4049-3e3e-4905-8930-01b0387b9d60">

Importantly, this allows us to accommodate matching regions that are not easily represented by a simple polygon like a rectangle. 

Feel free to let me know if you're able to use what you learn from the MERFISH to Visium alignment notebook to identify the regions that 'match' between the two Xenium replicates or if you run into any additional challenges.

Best,
Jean

**Comment by estellad** [comment]
Dear Jean, 

Thank you for the resources! Sorry for the late reply as I was on vacation. I tried and it does not work very well. 

On a side note, I noticed that `STalign.transform_points_source_to_target()` in [the mouse brain tutorial](https://jef.works/STalign/notebooks/merfish-visium-alignment-with-point-annotator.html) seems like an outdated function that does not exist anymore. I used `STalign.transform_points_target_to_atlas()` instead. 

Then here are the results running the similarity weights: 
1. Aligned two Xenium slices, mapping Xe2 to Xe1
![Screenshot 2023-11-03 at 07 00 49](https://github.com/JEFworks-Lab/STalign/assets/29610938/d55d833d-8c1c-44d6-a630-caf6c5e1a775)
2. Plotting similarity weights on Xe2 coordinates
![Screenshot 2023-11-03 at 07 02 08](https://github.com/JEFworks-Lab/STalign/assets/29610938/70827bbe-2dce-4ecd-85c0-edd78ce7c88d)
3. The histogram of weights
![Screenshot 2023-11-03 at 07 02 44](https://github.com/JEFworks-Lab/STalign/assets/29610938/2fa4fbc9-7050-4f76-b6fd-1ad537b79519)

The code I used is [here](https://github.com/estellad/STalign_test/blob/master/STalignXe1CoordXe2Coord_overlap.py), note that tpointsI in mouse brain is tpointsJ in this case. 


Sincerely,
Estella

**Comment by JEFworks** [comment]
Dear Estella,

Thanks for the well documented investigative work! 

I believe there may a misunderstanding in terms of the alignment "direction". Note that for STalign, we can learn a transformation that maps from a target dataset to a source. But this transformation is invertible, so we can also use the same learned transformation to map from the source to the target. 

We sometimes use the words 'source' and 'atlas' interchangeably. So there is an earlier version of the software where we had functions like `STalign.transform_points_target_to_atlas()` and `STalign.transform_points_atlas_to_target()` that has since been updated to `STalign.transform_points_target_to_source()` and `STalign.transform_points_source_to_target()` respectively to better match what we describe in the paper. You may have the earlier version of the software. 

I believe there is a misapplication of a source transformation to a target to derive weights in the target instead of source in your example. I was able to fix your code and also do a demonstration of this source to target vs target to source alignment in this updated notebook: https://github.com/JEFworks-Lab/STalign/blob/main/docs/notebooks/xenium-xenium-alignment.ipynb

My similarity weights:
![image](https://github.com/JEFworks-Lab/STalign/assets/8975944/781e52e8-bcf4-497e-8a50-e2e3e5994d94)

Histogram of weights: 
![image](https://github.com/JEFworks-Lab/STalign/assets/8975944/352ef216-c7d6-4e5c-b3a2-facb15068e10)

And finally the subset of 'matching' cells based on weight > 0.5:
![image](https://github.com/JEFworks-Lab/STalign/assets/8975944/96167a1a-12fa-40c4-adfb-581f1e190668)

My threshold is likely a bit stringent. There also appear to be some cells on the left that were allocated into the artifact instead of matching term because they don't align well (perhaps due to structural changes across the serial sections). So you may wish to tinker with some of the weight parameters (sigmaA relative to sigmaB, sigmaM) depending on whether you want to keep these cells in your subsetting. 

Feel free to reach out if you have any other questions,
Jean

**Comment by estellad** [comment]
Dear Jean,

Thank you very much for your help! From the step of affine transformation, I also tried the other direction (mapping xe1 onto xe2) by swapping L and T, and obtained the following weights. 
![Screenshot 2023-11-07 at 13 40 35](https://github.com/JEFworks-Lab/STalign/assets/29610938/2e740f33-aca5-4fc8-8c3f-eb2cddcf463f)
The weights are less binary compared to your histogram on xe2 mapping to xe1. Here are some subsetted xe1 (threshold 0.6 and 0.8, respectively) and xe2 (both threshold at 0.8) after alignment, with varying thresholds. 
![Screenshot 2023-11-07 at 13 36 37](https://github.com/JEFworks-Lab/STalign/assets/29610938/46c41abd-da70-4e7a-8203-e1841415647e)
![Screenshot 2023-11-07 at 13 37 12](https://github.com/JEFworks-Lab/STalign/assets/29610938/014ef830-128a-4fbe-8ec7-a7b08dcea480)
Here is the [code](https://github.com/estellad/STalign_test/blob/master/xenium-xenium-alignment_subsetting.ipynb) I used. 

I think we can close the issue now, if I didn't make mistakes :)

Sincerely,
Estella
